
const EMBEDDED_CHAPTERS = [{"number": 1, "title": "Overview"}, {"number": 2, "title": "PESTEL"}, {"number": 3, "title": "Country Segmentation"}, {"number": 4, "title": "Religious Overview"}, {"number": 5, "title": "SWOT Analysis"}, {"number": 6, "title": "Stakeholders Mapping"}, {"number": 7, "title": "Biblical and Spiritual Mapping"}, {"number": 8, "title": "Country Entry"}, {"number": 9, "title": "Problems / Challenges"}];
const el={countryName:document.getElementById('countryName'),flagImg:document.getElementById('flagImg'),generatedAt:document.getElementById('generatedAt'),viewTitle:document.getElementById('viewTitle'),viewSubtitle:document.getElementById('viewSubtitle'),breadcrumbs:document.getElementById('breadcrumbs'),chapterTabs:document.getElementById('chapterTabs'),sectionTabs:document.getElementById('sectionTabs'),subsectionTabs:document.getElementById('subsectionTabs'),content:document.getElementById('content'),refs:document.getElementById('refs')};
const state={index:{country:{name:'São Tomé and Príncipe',flag:'assets/flag-stp.svg'},chapters:EMBEDDED_CHAPTERS,generatedAt:''},chapter:null};
function esc(s){return (s||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');}
function linkify(t){const r=/(https?:\/\/[^\s)\]]+)/g;return esc(t).replace(r,m=>`<a href="${m}" target="_blank" rel="noreferrer">${m}</a>`);}
function parseHash(){const h=(location.hash||'').replace(/^#\/?/,'');const p=h.split('/').filter(Boolean);const route={chapter:null,section:null,sub:null};for(let i=0;i<p.length;i++){if(p[i]==='chapter'&&p[i+1])route.chapter=Number(p[i+1]);if(p[i]==='section'&&p[i+1])route.section=p[i+1];if(p[i]==='sub'&&p[i+1])route.sub=p[i+1];}return route;}
async function loadGeneratedAt(){try{const res=await fetch('data/index.json',{cache:'no-store'});if(res.ok){const v=await res.json();if(v?.generatedAt){state.index.generatedAt=v.generatedAt;el.generatedAt.textContent=`Generated: ${v.generatedAt}`;}}}catch(e){}}
async function loadChapter(n){if(!n){state.chapter=null;return;}try{const res=await fetch(`data/chapter${n}.json`,{cache:'no-store'});if(!res.ok)throw new Error();state.chapter=await res.json();}catch(e){state.chapter={number:n,title:'',sections:[]};el.content.innerHTML='<p class="muted">Chapter data could not be loaded. Make sure the <code>data/</code> folder exists in GitHub Pages.</p>';}}
function crumbs(items){el.breadcrumbs.innerHTML=items.map((it,idx)=>idx===items.length-1?`<span>${esc(it.label)}</span>`:`<a href="${it.href}">${esc(it.label)}</a> <span style="opacity:.5">/</span> `).join('');}
function renderTabs(container,tabs,active){container.innerHTML='';if(!tabs||!tabs.length){container.style.display='none';return;}container.style.display='flex';for(const t of tabs){const b=document.createElement('button');b.className='tab'+(t.href===active?' tab--active':'');b.type='button';b.innerHTML=`<div class="tab__top">${esc(t.top)}</div>${t.sub?`<div class=\"tab__sub\">${esc(t.sub)}</div>`:''}`;b.onclick=()=>location.hash=t.href;container.appendChild(b);}}
function renderContent(text){if(!text){el.content.innerHTML='';return;}const lines=String(text).split('\n');el.content.innerHTML=lines.map(ln=>ln.startsWith('### ')?`<h3>${esc(ln.slice(4))}</h3>`:ln.startsWith('- ')?`<div>• ${linkify(ln.slice(2))}</div>`:ln.trim()?`<p>${linkify(ln)}</p>`:'').join('');}
function renderRefs(links){if(!links||!links.length){el.refs.innerHTML='';return;}const rows=links.map((l,i)=>`<tr><td>${i+1}</td><td><a href="${l}" target="_blank" rel="noreferrer">${l}</a></td></tr>`).join('');el.refs.innerHTML=`<h3>References</h3><table class="table"><thead><tr><th style="width:70px">#</th><th>Link</th></tr></thead><tbody>${rows}</tbody></table>`;}
function findSection(ch,slug){return (ch?.sections||[]).find(s=>s.slug===slug);}
function findSub(sec,slug){return (sec?.subsections||[]).find(s=>s.slug===slug);}
async function render(){const r=parseHash();const chapterTabs=(state.index.chapters||[]).map(c=>({top:`Chapter ${c.number}`,sub:c.title,href:`#/chapter/${c.number}`}));renderTabs(el.chapterTabs,chapterTabs,r.chapter?`#/chapter/${r.chapter}`:null);if(!r.chapter){el.viewTitle.textContent='Chapters';el.viewSubtitle.textContent='';crumbs([{label:'Home',href:'#/'}]);el.sectionTabs.style.display='none';el.subsectionTabs.style.display='none';el.content.innerHTML='';el.refs.innerHTML='';return;}await loadChapter(r.chapter);const chMeta=(state.index.chapters||[]).find(c=>c.number===r.chapter);const secTabs=(state.chapter.sections||[]).map(s=>({top:s.number,sub:s.title,href:`#/chapter/${r.chapter}/section/${s.slug}`}));if(!r.section){el.viewTitle.textContent=`Chapter ${r.chapter}: ${chMeta?.title||''}`;el.viewSubtitle.textContent='';crumbs([{label:'Home',href:'#/'},{label:`Chapter ${r.chapter}`,href:`#/chapter/${r.chapter}`}]);renderTabs(el.sectionTabs,secTabs,null);el.subsectionTabs.style.display='none';const sum=state.chapter.sections?.[0];if(sum&&String(sum.number).endsWith('.0')){renderContent(sum.content);renderRefs(sum.references);}else{renderContent('');renderRefs([]);}return;}const sec=findSection(state.chapter,r.section);if(!sec){location.hash=`#/chapter/${r.chapter}`;return;}if((sec.subsections||[]).length&&!r.sub){location.hash=`#/chapter/${r.chapter}/section/${sec.slug}/sub/${sec.subsections[0].slug}`;return;}el.viewTitle.textContent=`${sec.number} — ${sec.title}`;el.viewSubtitle.textContent='';crumbs([{label:'Home',href:'#/'},{label:`Chapter ${r.chapter}`,href:`#/chapter/${r.chapter}`},{label:sec.number,href:`#/chapter/${r.chapter}/section/${sec.slug}`}]);renderTabs(el.sectionTabs,secTabs,`#/chapter/${r.chapter}/section/${sec.slug}`);const subTabs=(sec.subsections||[]).map(s=>({top:s.number,sub:s.title,href:`#/chapter/${r.chapter}/section/${sec.slug}/sub/${s.slug}`}));if(!subTabs.length){el.subsectionTabs.style.display='none';renderContent(sec.content);renderRefs(sec.references);return;}renderTabs(el.subsectionTabs,subTabs,`#/chapter/${r.chapter}/section/${sec.slug}/sub/${r.sub}`);const sub=findSub(sec,r.sub);if(!sub){location.hash=`#/chapter/${r.chapter}/section/${sec.slug}/sub/${sec.subsections[0].slug}`;return;}el.viewTitle.textContent=`${sub.number} — ${sub.title}`;crumbs([{label:'Home',href:'#/'},{label:`Chapter ${r.chapter}`,href:`#/chapter/${r.chapter}`},{label:sec.number,href:`#/chapter/${r.chapter}/section/${sec.slug}`},{label:sub.number,href:`#/chapter/${r.chapter}/section/${sec.slug}/sub/${sub.slug}`}]);renderContent(sub.content);renderRefs(sub.references);}
async function start(){el.countryName.textContent=state.index.country.name;el.flagImg.src=state.index.country.flag;await loadGeneratedAt();window.addEventListener('hashchange',()=>render());if(!location.hash)location.hash='#/';await render();}
start();
